
import "./globals.css";
import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="corner">
            <a href="https://instagram.com">
              <Image
                src="/instagram.svg"
                alt="instagram"
                width={100}
                height={24}
                priority
              />
            </a>
          </div>

          <div className="corner logo">
            <Image src="/images/logo.png" alt="logo" width={300} height={240} />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
